var DICTS = {
    "Lección 1": [
        { es: "yo soy", ru: "я есть" },
        { es: "tú eres", ru: "ты есть" },
        { es: "él es", ru: "он есть" },
        { es: "nosotros somos", ru: "мы есть" },
        { es: "vosotros sois", ru: "вы есть" },
        { es: "ellos son", ru: "они есть" },

        { es: "yo tengo", ru: "я имею" },
        { es: "tú tienes", ru: "ты имеешь" },
        { es: "él tiene", ru: "он имеет" },
        { es: "nosotros tenemos", ru: "мы имеем" },
        { es: "vosotros teneis", ru: "вы имеете" },
        { es: "ellos tienen", ru: "они имеют" },

        { es: "yo vivo", ru: "я живу" },
        { es: "tú vives", ru: "ты живешь" },
        { es: "él vive", ru: "он живет" },
        { es: "nosotros vivimos", ru: "мы живем" },
        { es: "vosotros vivís", ru: "вы живёте" },
        { es: "ellos viven", ru: "они живут" },

        { es: "yo me despierto", ru: "я просыпаюсь" },
        { es: "tú te despiertas", ru: "ты просыпаешься" },
        { es: "él se despierta", ru: "он просыпается" },
        { es: "nosotros nos despertamos", ru: "мы просыпаемся" },
        { es: "vosotros os despertais", ru: "вы просыпаетесь" },
        { es: "ellos se despiertan", ru: "они просыпаются" },

        { es: "yo me levanto", ru: "я поднимаюсь" },
        { es: "tú te levantas", ru: "ты поднимаешься" },
        { es: "él se levanta", ru: "он поднимается" },
        { es: "nosotros nos levatamos", ru: "мы поднимаемся" },
        { es: "vosotros os levantais", ru: "вы поднимаетесь" },
        { es: "ellos se levantan", ru: "они поднимаются" },

        { es: "yo me ducho", ru: "я принимаю душ (вз.)" },
        { es: "tú te duchas", ru: "ты принимаешь душ (вз.)" },
        { es: "él se ducha", ru: "он принимает душ (вз.)" },
        { es: "nosotros nos duchamos", ru: "мы принимаем душ (вз.)" },
        { es: "vosotros os duchais", ru: "вы принимаете душ (вз.)" },
        { es: "ellos se duchan", ru: "они принимают душ (вз.)" },

        { es: "yo tomo", ru: "я беру" },
        { es: "tú tomas", ru: "ты берешь" },
        { es: "él toma", ru: "он берет" },
        { es: "nosotros tomamos", ru: "мы берем" },
        { es: "vosotros tomais", ru: "вы берете" },
        { es: "ellos toman", ru: "они берут" },

        { es: "yo me visto", ru: "я одеваюсь" },
        { es: "tú te vistes", ru: "ты одеваешься" },
        { es: "él se viste", ru: "он одевается" },
        { es: "nosotros nos vestimos", ru: "мы одеваемся" },
        { es: "vosotros os vestís", ru: "вы одеваетесь" },
        { es: "ellos visten", ru: "они одеваются" },

        { es: "yo desayuno", ru: "я завтракаю" },
        { es: "tú desayunas", ru: "ты завтракаешь" },
        { es: "él desayuna", ru: "он завтракает" },
        { es: "nosotros desayunamos", ru: "мы завтракаем" },
        { es: "vosotros desayunais", ru: "вы завтракаете" },
        { es: "ellos desayunan", ru: "они завтракают" },

        { es: "yo me pongo", ru: "я надеваю" },
        { es: "tú te pones", ru: "ты надеваешь" },
        { es: "él se pone", ru: "он надевает" },
        { es: "nosotros nos ponemos", ru: "мы надеваем" },
        { es: "vosotros os poneis", ru: "вы надеваете" },
        { es: "ellos se ponen", ru: "они надевают" },

        { es: "yo pongo", ru: "я кладу" },
        { es: "tú pones", ru: "ты кладешь" },
        { es: "él pone", ru: "он кладет" },
        { es: "nosotros ponemos", ru: "мы кладем" },
        { es: "vosotros poneis", ru: "вы кладете" },
        { es: "ellos ponen", ru: "они кладут" },

        { es: "yo salgo", ru: "я выхожу" },
        { es: "tú sales", ru: "ты выходишь" },
        { es: "él sale", ru: "он выходит" },
        { es: "nosotros salimos", ru: "мы выходим" },
        { es: "vosotros salís", ru: "вы выходите" },
        { es: "ellos salen", ru: "они выходят" },

        { es: "yo voy", ru: "я иду" },
        { es: "tú vas", ru: "ты идешь" },
        { es: "él va", ru: "он идет" },
        { es: "nosotros vamos", ru: "мы идем" },
        { es: "vosotros vais", ru: "вы идете" },
        { es: "ellos van", ru: "они идут" },
    ],
};

/*
        { es: "yo ", ru: "я " },
        { es: "tú ", ru: "ты " },
        { es: "él ", ru: "он " },
        { es: "nosotros ", ru: "мы " },
        { es: "vosotros ", ru: "вы " },
        { es: "ellos ", ru: "они " },

        { es: "yo me ", ru: "я " },
        { es: "tú te ", ru: "ты " },
        { es: "él se ", ru: "он " },
        { es: "nosotros nos ", ru: "мы " },
        { es: "vosotros os ", ru: "вы " },
        { es: "ellos se ", ru: "они " },
*/