export default {
    "28 de mayo": [
        { es: "asi, asi", ru: "так себе" },
        { es: "Lo siento", ru: "Прости/простите" },
        { es: "ahora", ru: "cейчас" },
        { es: "vale", ru: "хорошо/окей" },
        { es: "Hasta luego", ru: "До встречи" },
        { es: "el campo", ru: "сельская местность/деревня" },
        { es: "el vaso", ru: "стакан" },
        { es: "el tesoro", ru: "сокровище" },
        { es: "el regalo", ru: "подарок" },
        { es: "el dado", ru: "игральная кость" },
        { es: "el plato", ru: "тарелка" },
        { es: "la mesa", ru: "стол" },
        { es: "la silla", ru: "стул" },
        { es: "la puerta", ru: "дверь" },
        { es: "la ventana", ru: "окно" },
        { es: "la cama", ru: "кровать" },
        { es: "la pelota", ru: "мяч" },
        { es: "la maleta", ru: "чемодан" },
        { es: "la mariposa", ru: "бабочка" },
        { es: "el páharo", ru: "птичка" },
        { es: "el banco", ru: "скамейка" },
        { es: "la bolsa", ru: "пакет" },
        { es: "el cuaderno", ru: "тетрадь" },
        { es: "el mercado", ru: "рынок" },
        { es: "la tienda", ru: "магазин" },
    ],
    "familia": [
        { es: "estar soltero", ru: "быть холостым" },
        { es: "estar casada", ru: "быть замужем" },
        { es: "la prima", ru: "двоюродная сестра" },
        { es: "el primo", ru: "двоюродный брат" },
        { es: "la sobrina", ru: "племянница" },
        { es: "el sobrino", ru: "племянник" },
        { es: "la familia", ru: "ceмья" },
        { es: "la abuela", ru: "бабушка" },
        { es: "el abuelo", ru: "дедушка" },
        { es: "la tia", ru: "тетя" },
        { es: "el tio", ru: "дядя" },
        { es: "el hijo", ru: "сын" },
        { es: "el hija", ru: "дочь" },
        { es: "el hermano", ru: "брат" },
        { es: "el hermana", ru: "сестра" },
        { es: "la madre", ru: "мать" },
        { es: "el padre", ru: "отец" },
        { es: "parientes", ru: "родственники" },
        { es: "padres", ru: "родители" },
        { es: "menor", ru: "младший" },
        { es: "mayor", ru: "старший" },
        { es: "el nieto", ru: "внук" },
        { es: "el nieta", ru: "внучка" },
        { es: "el marido", ru: "муж" },
        { es: "la mujer", ru: "жена/женщина" },
        { es: "la esposa", ru: "жена" },
        { es: "la pareja", ru: "партнер" },
        { es: "el novio", ru: "жених" },
        { es: "el novia", ru: "невеста" },
        { es: "un matrimonio", ru: "брак" },
        { es: "casarse", ru: "жениться/выйти замуж" },
        { es: "gustar/me gusta", ru: "нравиться/ мне нравится" },
        { es: "besar", ru: "целовать" },
        { es: "salir con alguien", ru: "встречаться с кем-то" },
        { es: "llevarse bien con alguien", ru: "хорошо ладить с кем-то" },
        { es: "querido", ru: "дорогой, милый" },
        { es: "querida", ru: "дорогая, милая" },
        { es: "cariño", ru: "дорогой" },
        { es: "mi amor", ru: "любовь моя" },
    ],
    "frases útiles": [
        { es: "¿Cómo estás?", ru: "Как у тебя дела?" },
        { es: "¿Como está usted?", ru: "Как у Вас дела?" },
        { es: "¿Qué tal?", ru: "Как жизнь?" },
        { es: "¡Qué tengas un buen día!", ru: "Хорошего дня!" },
        { es: "¡Qué tengas un buen fin de semana!", ru: "Хoроших выходных!" },
        { es: "Hasta pronto/luego", ru: " Пока/ увидимся" },
        { es: "Hasta la vista", ru: "До свидания" },
        { es: "Hasta mañana", ru: "До завтра" },
        { es: "Hasta el sábado", ru: "Увидимся в субботу" },
        { es: "Discúlpame/ discúlpeme", ru: "Извини/извините меня" },
        { es: "¿Cómo?", ru: "Простите, что?" },
        { es: "No entiendo/comprendo", ru: "Я не понимаю" },
        { es: "Habla hable más despacio, por favor", ru: "Говори/говорите помедленнее, пожалуйста" },
        { es: "Lo siento", ru: "Простите/Извините/Мне жаль" },
        { es: "Muchas gracias", ru: "Большое спасибо" },
        { es: "De nada", ru: "Не за что" },
        { es: "No hay de qué", ru: "Не за что" },
        { es: "Me gustó mucho", ru: "Мне очень понравилось" },
        { es: "¡Qué te diviertas/se divierta! ", ru: "Желаю хорошо провести время!" },
        { es: "Buen viaje", ru: "Счастливого пути" },
        { es: "¡Mucha suerte!", ru: "Удачи!" },
        { es: "¡Que tenga suerte!", ru: "Всего наилучшего!/ Удачи!" },
    ],
    "21 junio": [
        { es: "querido", ru: "дорогой" },
        { es: "el diaro", ru: "дневник",},
        { es: "hermoso", ru: "красивый",},
        { es: "hay", ru: "есть" },
        { es: "famoso", ru: "известный",},
        { es: "allí", ru: "там",},
        { es: "escultura", ru: "скульптура" },
        { es: "el oso", ru: "медведь",},
        { es: "el madroño", ru: "земмляничное дерево",},
        { es: "el simbolo", ru: "символ" },
        { es: "querer", ru: "хотеть",},
        { es: "visitar", ru: "посещать",},
        { es: "terminar", ru: "закончить/закончиться" },
        { es: "por ese", ru: "поэтому",},
        { es: "poder", ru: "уметь/мочь",},
        { es: "el pato", ru: "утка" },
        { es: "nadar", ru: "плавать",},
        { es: "juntos", ru: "вместе",},
        { es: "esperar", ru: "ожидать/надеяться" },
        { es: "mejorar", ru: "улучшать",},
        { es: "pronto", ru: "скоро",},
        { es: "extraño", ru: "странный" },
        { es: "la taza", ru: "чашка",},
        { es: "todavía", ru: "все еще",},
    ]
};

/*
        { es: "", ru: "" },
        { es: "", ru: "", tag: "n" },
        { es: "", ru: "", tag: "a" },

        { es: "", ru: "", tag: "v" },
        { es: "yo ", ru: "я " },
        { es: "tú ", ru: "ты " },
        { es: "él ", ru: "он " },
        { es: "nosotros ", ru: "мы " },
        { es: "vosotros ", ru: "вы " },
        { es: "ellos ", ru: "они " },

        { es: "yo me ", ru: "я " },
        { es: "tú te ", ru: "ты " },
        { es: "él se ", ru: "он " },
        { es: "nosotros nos ", ru: "мы " },
        { es: "vosotros os ", ru: "вы " },
        { es: "ellos se ", ru: "они " },
*/