var DICTS = {
    "Lección 1": [
        { es: "yo soy", ru: "я есть" },
        { es: "tú eres", ru: "ты есть" },
        { es: "él es", ru: "он есть" },
        { es: "nosotros somos", ru: "мы есть" },
        { es: "vosotros sois", ru: "вы есть" },
        { es: "ellos son", ru: "они есть" },

        { es: "yo tengo", ru: "я имею" },
        { es: "tú tienes", ru: "ты имеешь" },
        { es: "él tiene", ru: "он имеет" },
        { es: "nosotros tenemos", ru: "мы имеем" },
        { es: "vosotros teneis", ru: "вы имеете" },
        { es: "ellos tienen", ru: "они имеют" },

        { es: "yo vivo", ru: "я живу" },
        { es: "tú vives", ru: "ты живешь" },
        { es: "él vive", ru: "он живет" },
        { es: "nosotros vivimos", ru: "мы живем" },
        { es: "vosotros vivís", ru: "вы живёте" },
        { es: "ellos viven", ru: "они живут" },

        { es: "yo me despierto", ru: "я просыпаюсь" },
        { es: "tú te despiertas", ru: "ты просыпаешься" },
        { es: "él se despierta", ru: "он просыпается" },
        { es: "nosotros nos despertamos", ru: "мы просыпаемся" },
        { es: "vosotros os despertais", ru: "вы просыпаетесь" },
        { es: "ellos se despiertan", ru: "они просыпаются" },

        { es: "yo me levanto", ru: "я поднимаюсь" },
        { es: "tú te levantas", ru: "ты поднимаешься" },
        { es: "él se levanta", ru: "он поднимается" },
        { es: "nosotros nos levatamos", ru: "мы поднимаемся" },
        { es: "vosotros os levantais", ru: "вы поднимаетесь" },
        { es: "ellos se levantan", ru: "они поднимаются" },

        { es: "yo me ducho", ru: "я принимаю душ (вз.)" },
        { es: "tú te duchas", ru: "ты принимаешь душ (вз.)" },
        { es: "él se ducha", ru: "он принимает душ (вз.)" },
        { es: "nosotros nos duchamos", ru: "мы принимаем душ (вз.)" },
        { es: "vosotros os duchais", ru: "вы принимаете душ (вз.)" },
        { es: "ellos se duchan", ru: "они принимают душ (вз.)" },

        { es: "yo tomo", ru: "я беру" },
        { es: "tú tomas", ru: "ты берешь" },
        { es: "él toma", ru: "он берет" },
        { es: "nosotros tomamos", ru: "мы берем" },
        { es: "vosotros tomais", ru: "вы берете" },
        { es: "ellos toman", ru: "они берут" },

        { es: "yo me visto", ru: "я одеваюсь" },
        { es: "tú te vistes", ru: "ты одеваешься" },
        { es: "él se viste", ru: "он одевается" },
        { es: "nosotros nos vestimos", ru: "мы одеваемся" },
        { es: "vosotros os vestís", ru: "вы одеваетесь" },
        { es: "ellos visten", ru: "они одеваются" },

        { es: "yo desayuno", ru: "я завтракаю" },
        { es: "tú desayunas", ru: "ты завтракаешь" },
        { es: "él desayuna", ru: "он завтракает" },
        { es: "nosotros desayunamos", ru: "мы завтракаем" },
        { es: "vosotros desayunais", ru: "вы завтракаете" },
        { es: "ellos desayunan", ru: "они завтракают" },

        { es: "yo me pongo", ru: "я надеваю" },
        { es: "tú te pones", ru: "ты надеваешь" },
        { es: "él se pone", ru: "он надевает" },
        { es: "nosotros nos ponemos", ru: "мы надеваем" },
        { es: "vosotros os poneis", ru: "вы надеваете" },
        { es: "ellos se ponen", ru: "они надевают" },

        { es: "yo pongo", ru: "я кладу" },
        { es: "tú pones", ru: "ты кладешь" },
        { es: "él pone", ru: "он кладет" },
        { es: "nosotros ponemos", ru: "мы кладем" },
        { es: "vosotros poneis", ru: "вы кладете" },
        { es: "ellos ponen", ru: "они кладут" },

        { es: "yo salgo", ru: "я выхожу" },
        { es: "tú sales", ru: "ты выходишь" },
        { es: "él sale", ru: "он выходит" },
        { es: "nosotros salimos", ru: "мы выходим" },
        { es: "vosotros salís", ru: "вы выходите" },
        { es: "ellos salen", ru: "они выходят" },

        { es: "yo voy", ru: "я иду" },
        { es: "tú vas", ru: "ты идешь" },
        { es: "él va", ru: "он идет" },
        { es: "nosotros vamos", ru: "мы идем" },
        { es: "vosotros vais", ru: "вы идете" },
        { es: "ellos van", ru: "они идут" },
    ],
    "Lección 2": [
        { es: "yo estoy", ru: "я быть" },
        { es: "tú estás", ru: "ты быть" },
        { es: "él está", ru: "он быть" },
        { es: "nosotros estamos", ru: "мы быть" },
        { es: "vosotros estais", ru: "вы быть" },
        { es: "ellos están", ru: "они быть" },

        { es: "un casa", ru: "дом" },
        { es: "un trabajo", ru: "работа" },
        { es: "una mujer", ru: "дeвушка" },
        { es: "un esposo", ru: "супруг" },
        { es: "una esposa", ru: "супруга" },
        { es: "un hijo", ru: "сын" },
        { es: "una hija", ru: "дочь" },
        { es: "los hijos", ru: "дети" },
        { es: "las hijas", ru: "дочери" },
        { es: "un té", ru: "чай" },
        { es: "un café", ru: "кофе" },
        { es: "una taza", ru: "чашка" },
        { es: "pero", ru: "но" },
        { es: "nueva", ru: "новый" },
        { es: "pantalones", ru: "штаны" },

        { es: "¿Qué tal?", ru: "Как вы?" },
        { es: "¿Cómo?", ru: "Как?" },

        { es: "yo bebo", ru: "я пью" },
        { es: "tú bebes", ru: "ты пьешь" },
        { es: "él bebe", ru: "он пьет" },
        { es: "nosotros bebemos", ru: "мы пьем" },
        { es: "vosotros bebéis", ru: "вы пьете" },
        { es: "ellos beben", ru: "они пьют" },

        { es: "yo me llamo", ru: "меня зовут" },
        { es: "tú te llamas", ru: "тебя зовут" },
        { es: "él se llama", ru: "его зовут" },
        { es: "nosotros nos llamamos", ru: "нас зовут" },
        { es: "vosotros os llamais", ru: "вас зовут" },
        { es: "ellos se llaman", ru: "их зовут" },

        { es: "yo llego", ru: "я прибывают" },
        { es: "tú llegas", ru: "ты прибываешь" },
        { es: "él llega", ru: "он прибывает" },
        { es: "nosotros llegamos", ru: "мы прибываем" },
        { es: "vosotros llegais", ru: "вы прибываете" },
        { es: "ellos llegan", ru: "они прибывают" },

        { es: "yo vengo", ru: "я пришел" },
        { es: "tú vienes", ru: "ты пришел" },
        { es: "él viene", ru: "он пришел" },
        { es: "nosotros venimos", ru: "мы пришли" },
        { es: "vosotros venís", ru: "вы пришли" },
        { es: "ellos vienen", ru: "они пришли" },

        { es: "Comer", ru: "кушать, есть, обедать" },
        { es: "Almorzar", ru: "обедать" },
        { es: "el almuerzo", ru: "обед" },
        { es: "una comida", ru: "еда" },

        { es: "Cenar", ru: "ужинать" },
        { es: "yo ceno", ru: "я ужинаю" },
        { es: "tú cenas", ru: "ты ужинаешь" },
        { es: "él cena", ru: "он ужинает" },
        { es: "nosotros cenamos", ru: "мы ужинаем" },
        { es: "vosotros cenais", ru: "вы ужинаете" },
        { es: "ellos cenan", ru: "они ужинают" },

        { es: "una merienda", ru: "закуска" },
        { es: "rojo", ru: "красный" },
        { es: "blanco", ru: "белый" },
        { es: "rosado", ru: "розовый" },
        { es: "negro", ru: "черный" },
        { es: "ir a la cama", ru: "идти спать" },

        { es: "Dormir", ru: "спать" },
        { es: "yo duermo", ru: "я сплю" },
        { es: "tú duermes", ru: "ты спишь" },
        { es: "él duerme", ru: "он спит" },
        { es: "nosotros dormimos", ru: "мы спим" },
        { es: "vosotros dormís", ru: "вы спите" },
        { es: "ellos duermen", ru: "они спят" },

        { es: "Acostarse", ru: "лечь спать" },
        { es: "yo me acuesto", ru: "я ложусь спать" },
        { es: "tú te acuestas", ru: "ты ложишься спать" },
        { es: "él se acuesta", ru: "он ложиться спать" },
        { es: "nosotros nos acostamos", ru: "мы ложимся спать" },
        { es: "vosotros os acostais", ru: "вы ложитесь спать" },
        { es: "ellos se acuestan", ru: "они ложаться спать" },
    ],
    "Lección 3": [
        { es: "el coche", ru: "автомобиль" },
        { es: "el zumo", ru: "сок" },
        { es: "naranja", ru: "апельсин" },
        { es: "melocotón", ru: "персик" },
        { es: "un abrigo", ru: "пальто" },
        { es: "avión", ru: "самолет" },
        { es: "uno", ru: "1" },
        { es: "dos", ru: "2" },
        { es: "tres", ru: "3" },
        { es: "cuatro", ru: "4" },
        { es: "cinco", ru: "5" },
        { es: "seis", ru: "6" },
        { es: "siete", ru: "7" },
        { es: "ocho", ru: "8" },
        { es: "nueve", ru: "9" },
        { es: "diez", ru: "10" },
        { es: "once", ru: "11" },
        { es: "doce", ru: "12" },
        { es: "después", ru: "после" },
        { es: "perro", ru: "собака" },

        { es: "Dar", ru: "давать" },
        { es: "yo doy", ru: "я даю" },
        { es: "tú das", ru: "ты даешь" },
        { es: "él da", ru: "он дает" },
        { es: "nosotros damos", ru: "мы даем" },
        { es: "vosotros dais", ru: "вы даете" },
        { es: "ellos dan", ru: "они дают" },

        { es: "Pasear", ru: "гулять" },
        { es: "un paseo", ru: "прогулка" },
        { es: "Coninar", ru: "готовить (cook)" },
        { es: "Preparar", ru: "готовить (prepare)" },
        { es: "yo preparo la cena", ru: "я готовлю ужин" },
        { es: "una copa", ru: "стакан" },
        { es: "un vino tinto", ru: "красное вино" },
    ],
};

/*
        { es: "", ru: "" },
        { es: "yo ", ru: "я " },
        { es: "tú ", ru: "ты " },
        { es: "él ", ru: "он " },
        { es: "nosotros ", ru: "мы " },
        { es: "vosotros ", ru: "вы " },
        { es: "ellos ", ru: "они " },

        { es: "yo me ", ru: "я " },
        { es: "tú te ", ru: "ты " },
        { es: "él se ", ru: "он " },
        { es: "nosotros nos ", ru: "мы " },
        { es: "vosotros os ", ru: "вы " },
        { es: "ellos se ", ru: "они " },
*/