export default {
    "28 de mayo": [
        { es: "asi, asi", ru: "так себе" },
        { es: "Lo siento", ru: "Прости/простите" },
        { es: "ahora", ru: "cейчас" },
        { es: "vale", ru: "хорошо/окей" },
        { es: "Hasta luego", ru: "До встречи" },
        { es: "el campo", ru: "сельская местность/деревня" },
        { es: "el vaso", ru: "стакан" },
        { es: "el tesoro", ru: "сокровище" },
        { es: "el regalo", ru: "подарок" },
        { es: "el dado", ru: "игральная кость" },
        { es: "el plato", ru: "тарелка" },
        { es: "la mesa", ru: "стол" },
        { es: "la silla", ru: "стул" },
        { es: "la puerta", ru: "дверь" },
        { es: "la ventana", ru: "окно" },
        { es: "la cama", ru: "кровать" },
        { es: "la pelota", ru: "мяч" },
        { es: "la maleta", ru: "чемодан" },
        { es: "la mariposa", ru: "бабочка" },
        { es: "el páharo", ru: "птичка" },
        { es: "el banco", ru: "скамейка" },
        { es: "la bolsa", ru: "пакет" },
        { es: "el cuaderno", ru: "тетрадь" },
        { es: "el mercado", ru: "рынок" },
        { es: "la tienda", ru: "магазин" },
    ],
    "familia": [
        { es: "estar soltero", ru: "быть холостым" },
        { es: "estar casada", ru: "быть замужем" },
        { es: "la prima", ru: "двоюродная сестра" },
        { es: "el primo", ru: "двоюродный брат" },
        { es: "la sobrina", ru: "племянница" },
        { es: "el sobrino", ru: "племянник" },
        { es: "la familia", ru: "ceмья" },
        { es: "la abuela", ru: "бабушка" },
        { es: "el abuelo", ru: "дедушка" },
        { es: "la tia", ru: "тетя" },
        { es: "el tio", ru: "дядя" },
        { es: "el hijo", ru: "сын" },
        { es: "el hija", ru: "дочь" },
        { es: "el hermano", ru: "брат" },
        { es: "el hermana", ru: "сестра" },
        { es: "la madre", ru: "мать" },
        { es: "el padre", ru: "отец" },
        { es: "parientes", ru: "родственники" },
        { es: "padres", ru: "родители" },
        { es: "menor", ru: "младший" },
        { es: "mayor", ru: "старший" },
        { es: "el nieto", ru: "внук" },
        { es: "el nieta", ru: "внучка" },
        { es: "el marido", ru: "муж" },
        { es: "la mujer", ru: "жена/женщина" },
        { es: "la esposa", ru: "жена" },
        { es: "la pareja", ru: "партнер" },
        { es: "el novio", ru: "жених" },
        { es: "el novia", ru: "невеста" },
        { es: "un matrimonio", ru: "брак" },
        { es: "casarse", ru: "жениться/выйти замуж" },
        { es: "gustar/me gusta", ru: "нравиться/ мне нравится" },
        { es: "besar", ru: "целовать" },
        { es: "salir con alguien", ru: "встречаться с кем-то" },
        { es: "llevarse bien con alguien", ru: "хорошо ладить с кем-то" },
        { es: "querido", ru: "дорогой, милый" },
        { es: "querida", ru: "дорогая, милая" },
        { es: "cariño", ru: "дорогой" },
        { es: "mi amor", ru: "любовь моя" },
    ]
};

/*
        { es: "", ru: "" },
        { es: "", ru: "", tag: "n" },
        { es: "", ru: "", tag: "a" },

        { es: "", ru: "", tag: "v" },
        { es: "yo ", ru: "я " },
        { es: "tú ", ru: "ты " },
        { es: "él ", ru: "он " },
        { es: "nosotros ", ru: "мы " },
        { es: "vosotros ", ru: "вы " },
        { es: "ellos ", ru: "они " },

        { es: "yo me ", ru: "я " },
        { es: "tú te ", ru: "ты " },
        { es: "él se ", ru: "он " },
        { es: "nosotros nos ", ru: "мы " },
        { es: "vosotros os ", ru: "вы " },
        { es: "ellos se ", ru: "они " },
*/