export default {
    "Lección 1": [
        { es: "Ser", ru: "быть", tag: "v" },
        { es: "yo soy", ru: "я есть" },
        { es: "tú eres", ru: "ты есть" },
        { es: "él es", ru: "он есть" },
        { es: "nosotros somos", ru: "мы есть" },
        { es: "vosotros sois", ru: "вы есть" },
        { es: "ellos son", ru: "они есть" },

        { es: "Tener", ru: "иметь", tag: "v" },
        { es: "yo tengo", ru: "я имею" },
        { es: "tú tienes", ru: "ты имеешь" },
        { es: "él tiene", ru: "он имеет" },
        { es: "nosotros tenemos", ru: "мы имеем" },
        { es: "vosotros teneis", ru: "вы имеете" },
        { es: "ellos tienen", ru: "они имеют" },

        { es: "Vivir", ru: "жить", tag: "v" },
        { es: "yo vivo", ru: "я живу" },
        { es: "tú vives", ru: "ты живешь" },
        { es: "él vive", ru: "он живет" },
        { es: "nosotros vivimos", ru: "мы живем" },
        { es: "vosotros vivís", ru: "вы живёте" },
        { es: "ellos viven", ru: "они живут" },

        { es: "Despertarse", ru: "просыпаться", tag: "v" },
        { es: "yo me despierto", ru: "я просыпаюсь" },
        { es: "tú te despiertas", ru: "ты просыпаешься" },
        { es: "él se despierta", ru: "он просыпается" },
        { es: "nosotros nos despertamos", ru: "мы просыпаемся" },
        { es: "vosotros os despertais", ru: "вы просыпаетесь" },
        { es: "ellos se despiertan", ru: "они просыпаются" },

        { es: "Levantarse", ru: "подниматься", tag: "v" },
        { es: "yo me levanto", ru: "я поднимаюсь" },
        { es: "tú te levantas", ru: "ты поднимаешься" },
        { es: "él se levanta", ru: "он поднимается" },
        { es: "nosotros nos levatamos", ru: "мы поднимаемся" },
        { es: "vosotros os levantais", ru: "вы поднимаетесь" },
        { es: "ellos se levantan", ru: "они поднимаются" },

        { es: "Ducharse", ru: "принимать душ", tag: "v" },
        { es: "yo me ducho", ru: "я принимаю душ (вз.)" },
        { es: "tú te duchas", ru: "ты принимаешь душ (вз.)" },
        { es: "él se ducha", ru: "он принимает душ (вз.)" },
        { es: "nosotros nos duchamos", ru: "мы принимаем душ (вз.)" },
        { es: "vosotros os duchais", ru: "вы принимаете душ (вз.)" },
        { es: "ellos se duchan", ru: "они принимают душ (вз.)" },

        { es: "Tomar", ru: "брать", tag: "v" },
        { es: "yo tomo", ru: "я беру" },
        { es: "tú tomas", ru: "ты берешь" },
        { es: "él toma", ru: "он берет" },
        { es: "nosotros tomamos", ru: "мы берем" },
        { es: "vosotros tomais", ru: "вы берете" },
        { es: "ellos toman", ru: "они берут" },

        { es: "Vestirse", ru: "одеваться", tag: "v" },
        { es: "yo me visto", ru: "я одеваюсь" },
        { es: "tú te vistes", ru: "ты одеваешься" },
        { es: "él se viste", ru: "он одевается" },
        { es: "nosotros nos vestimos", ru: "мы одеваемся" },
        { es: "vosotros os vestís", ru: "вы одеваетесь" },
        { es: "ellos visten", ru: "они одеваются" },

        { es: "Desayunar", ru: "завтракать", tag: "v" },
        { es: "yo desayuno", ru: "я завтракаю" },
        { es: "tú desayunas", ru: "ты завтракаешь" },
        { es: "él desayuna", ru: "он завтракает" },
        { es: "nosotros desayunamos", ru: "мы завтракаем" },
        { es: "vosotros desayunais", ru: "вы завтракаете" },
        { es: "ellos desayunan", ru: "они завтракают" },

        { es: "Ponerse", ru: "надевать", tag: "v" },
        { es: "yo me pongo", ru: "я надеваю" },
        { es: "tú te pones", ru: "ты надеваешь" },
        { es: "él se pone", ru: "он надевает" },
        { es: "nosotros nos ponemos", ru: "мы надеваем" },
        { es: "vosotros os poneis", ru: "вы надеваете" },
        { es: "ellos se ponen", ru: "они надевают" },

        { es: "Poner", ru: "класть", tag: "v" },
        { es: "yo pongo", ru: "я кладу" },
        { es: "tú pones", ru: "ты кладешь" },
        { es: "él pone", ru: "он кладет" },
        { es: "nosotros ponemos", ru: "мы кладем" },
        { es: "vosotros poneis", ru: "вы кладете" },
        { es: "ellos ponen", ru: "они кладут" },

        { es: "Salir", ru: "выходить", tag: "v" },
        { es: "yo salgo", ru: "я выхожу" },
        { es: "tú sales", ru: "ты выходишь" },
        { es: "él sale", ru: "он выходит" },
        { es: "nosotros salimos", ru: "мы выходим" },
        { es: "vosotros salís", ru: "вы выходите" },
        { es: "ellos salen", ru: "они выходят" },

        { es: "Ir", ru: "идти", tag: "v" },
        { es: "yo voy", ru: "я иду" },
        { es: "tú vas", ru: "ты идешь" },
        { es: "él va", ru: "он идет" },
        { es: "nosotros vamos", ru: "мы идем" },
        { es: "vosotros vais", ru: "вы идете" },
        { es: "ellos van", ru: "они идут" },
    ],
    "Lección 2": [
        { es: "Estar", ru: "находиться", tag: "v" },
        { es: "yo estoy", ru: "я быть" },
        { es: "tú estás", ru: "ты быть" },
        { es: "él está", ru: "он быть" },
        { es: "nosotros estamos", ru: "мы быть" },
        { es: "vosotros estais", ru: "вы быть" },
        { es: "ellos están", ru: "они быть" },

        { es: "una casa", ru: "дом", tag: "n" },
        { es: "un trabajo", ru: "работа", tag: "n" },
        { es: "una mujer", ru: "дeвушка", tag: "n" },
        { es: "un esposo", ru: "супруг", tag: "n" },
        { es: "una esposa", ru: "супруга", tag: "n" },
        { es: "un hijo", ru: "сын", tag: "n" },
        { es: "una hija", ru: "дочь", tag: "n" },
        { es: "los hijos", ru: "дети", tag: "n" },
        { es: "las hijas", ru: "дочери", tag: "n" },
        { es: "un té", ru: "чай", tag: "n" },
        { es: "un café", ru: "кофе", tag: "n" },
        { es: "una taza", ru: "чашка", tag: "n" },
        { es: "pero", ru: "но" },
        { es: "nueva", ru: "новый", tag: "a" },
        { es: "pantalones", ru: "штаны", tag: "n" },

        { es: "¿Qué tal?", ru: "Как вы?" },
        { es: "¿Cómo?", ru: "Как?" },

        { es: "Beber", ru: "пить", tag: "v" },
        { es: "yo bebo", ru: "я пью" },
        { es: "tú bebes", ru: "ты пьешь" },
        { es: "él bebe", ru: "он пьет" },
        { es: "nosotros bebemos", ru: "мы пьем" },
        { es: "vosotros bebéis", ru: "вы пьете" },
        { es: "ellos beben", ru: "они пьют" },

        { es: "Llamarse", ru: "зваться", tag: "v" },
        { es: "yo me llamo", ru: "меня зовут" },
        { es: "tú te llamas", ru: "тебя зовут" },
        { es: "él se llama", ru: "его зовут" },
        { es: "nosotros nos llamamos", ru: "нас зовут" },
        { es: "vosotros os llamais", ru: "вас зовут" },
        { es: "ellos se llaman", ru: "их зовут" },

        { es: "Llegar", ru: "прибывать", tag: "v" },
        { es: "yo llego", ru: "я прибывают" },
        { es: "tú llegas", ru: "ты прибываешь" },
        { es: "él llega", ru: "он прибывает" },
        { es: "nosotros llegamos", ru: "мы прибываем" },
        { es: "vosotros llegais", ru: "вы прибываете" },
        { es: "ellos llegan", ru: "они прибывают" },

        { es: "Venir", ru: "приходить", tag: "v" },
        { es: "yo vengo", ru: "я пришел" },
        { es: "tú vienes", ru: "ты пришел" },
        { es: "él viene", ru: "он пришел" },
        { es: "nosotros venimos", ru: "мы пришли" },
        { es: "vosotros venís", ru: "вы пришли" },
        { es: "ellos vienen", ru: "они пришли" },

        { es: "Comer", ru: "кушать, есть, обедать", tag: "v" },
        { es: "Almorzar", ru: "обедать" },
        { es: "el almuerzo", ru: "обед", tag: "n" },
        { es: "una comida", ru: "еда", tag: "n" },

        { es: "Cenar", ru: "ужинать", tag: "v" },
        { es: "yo ceno", ru: "я ужинаю" },
        { es: "tú cenas", ru: "ты ужинаешь" },
        { es: "él cena", ru: "он ужинает" },
        { es: "nosotros cenamos", ru: "мы ужинаем" },
        { es: "vosotros cenais", ru: "вы ужинаете" },
        { es: "ellos cenan", ru: "они ужинают" },

        { es: "una merienda", ru: "закуска", tag: "n" },
        { es: "rojo", ru: "красный", tag: "a" },
        { es: "blanco", ru: "белый", tag: "a" },
        { es: "rosado", ru: "розовый", tag: "a" },
        { es: "negro", ru: "черный", tag: "a" },
        { es: "ir a la cama", ru: "идти спать" },

        { es: "Dormir", ru: "спать", tag: "v" },
        { es: "yo duermo", ru: "я сплю" },
        { es: "tú duermes", ru: "ты спишь" },
        { es: "él duerme", ru: "он спит" },
        { es: "nosotros dormimos", ru: "мы спим" },
        { es: "vosotros dormís", ru: "вы спите" },
        { es: "ellos duermen", ru: "они спят" },

        { es: "Acostarse", ru: "лечь спать", tag: "v" },
        { es: "yo me acuesto", ru: "я ложусь спать" },
        { es: "tú te acuestas", ru: "ты ложишься спать" },
        { es: "él se acuesta", ru: "он ложиться спать" },
        { es: "nosotros nos acostamos", ru: "мы ложимся спать" },
        { es: "vosotros os acostais", ru: "вы ложитесь спать" },
        { es: "ellos se acuestan", ru: "они ложаться спать" },
    ],
    "Lección 3": [
        { es: "el coche", ru: "автомобиль", tag: "n" },
        { es: "el zumo", ru: "сок", tag: "n" },
        { es: "naranja", ru: "апельсин", tag: "n" },
        { es: "melocotón", ru: "персик", tag: "n" },
        { es: "un abrigo", ru: "пальто", tag: "n" },
        { es: "avión", ru: "самолет", tag: "n" },
        { es: "cero", ru: "0" },
        { es: "uno", ru: "1" },
        { es: "dos", ru: "2" },
        { es: "tres", ru: "3" },
        { es: "cuatro", ru: "4" },
        { es: "cinco", ru: "5" },
        { es: "seis", ru: "6" },
        { es: "siete", ru: "7" },
        { es: "ocho", ru: "8" },
        { es: "nueve", ru: "9" },
        { es: "diez", ru: "10" },
        { es: "once", ru: "11" },
        { es: "doce", ru: "12" },
        { es: "catorce", ru: "14" },
        { es: "después", ru: "после" },
        { es: "perro", ru: "собака" },

        { es: "Dar", ru: "давать", tag: "v" },
        { es: "yo doy", ru: "я даю" },
        { es: "tú das", ru: "ты даешь" },
        { es: "él da", ru: "он дает" },
        { es: "nosotros damos", ru: "мы даем" },
        { es: "vosotros dais", ru: "вы даете" },
        { es: "ellos dan", ru: "они дают" },

        { es: "Pasear", ru: "гулять", tag: "v" },
        { es: "un paseo", ru: "прогулка" },
        { es: "Cocinar", ru: "готовить (cook)" },
        { es: "Preparar", ru: "готовить (prepare)" },
        { es: "yo preparo la cena", ru: "я готовлю ужин" },
        { es: "una copa", ru: "бокал" },
        { es: "un vino tinto", ru: "красное вино" },
    ],
    "Lección 4": [
        { es: "¿Qué tiempo hace?", ru: "Как погода?" },
        { es: "hace calor", ru: "жарко" },
        { es: "hace frío", ru: "холодно" },
        { es: "hace fresco", ru: "прохладно" },
        { es: "llover", ru: "идти дождь" },
        { es: "nevar", ru: "идти снег" },
        { es: "grados", ru: "градусов" },
        { es: "bajo cero", ru: "ниже нуля" },
        { es: "sobre cero", ru: "выше нуля" },

        { es: "Hacer", ru: "делать", tag: "v" },
        { es: "yo hago", ru: "я делаю" },
        { es: "tú haces", ru: "ты делаешь" },
        { es: "él hace", ru: "он делает" },
        { es: "nosotros hacemos", ru: "мы делаем" },
        { es: "vosotros haceis", ru: "вы делаете" },
        { es: "ellos hacen", ru: "они делают" },

        { es: "deberes de casa", ru: "домашние задания" },
        { es: "un queso", ru: "сыр", tag: "n" },
        { es: "una maramelada", ru: "варенье", tag: "n" },
        { es: "un bocadilo", ru: "сэндвич", tag: "n" },
        { es: "un grito", ru: "крик", tag: "n" },

        { es: "Acabar", ru: "заканчивать", tag: "v" },
        { es: "yo acabo de", ru: "я только что" },
        { es: "tú acabas de", ru: "ты только что" },
        { es: "él acaba de", ru: "он только что" },
        { es: "nosotros acabamos de", ru: "мы только что" },
        { es: "vosotros acabais de", ru: "вы только что" },
        { es: "ellos acaban de", ru: "они только что" },

        { es: "para", ru: "на" },
        { es: "una plancha", ru: "утюг", tag: "n" },
        { es: "Planchar", ru: "утюжить", tag: "v" },
        { es: "Llevar", ru: "носить", tag: "v" },
        { es: "un vestido", ru: "платье", tag: "n" },
    ],
    "Lección 5": [
        { es: "ola de calor", ru: "жара" },
        { es: "Sacar", ru: "выгуливать", tag: "v" },

        { es: "mi ...", ru: "мой ..." },
        { es: "tu ...", ru: "твой ..." },
        { es: "su ...", ru: "его/их ..." },
        { es: "nuestro ...", ru: "наш ..." },
        { es: "vuestro ...", ru: "ваш ..." },

        { es: "mío/mía", ru: "мой/моя" },
        { es: "tuyo/tuya", ru: "твой/твоя" },
        { es: "suyo/suya", ru: "его/их" },
        { es: "nuestro/nuestra", ru: "наш/наша" },
        { es: "vuestro/vuestra", ru: "ваш/ваша" },

        { es: "este", ru: "этот" },
        { es: "esta", ru: "эта" },
        { es: "aquel", ru: "тот" },
        { es: "aquella", ru: "та" },

        { es: "sobre", ru: "(действие) на" },
        { es: "en", ru: "(место) на" },

        { es: "ir de compras", ru: "идти за покупками" },
        { es: "hacer compras", ru: "делать покупки" },
        { es: "estar cansado/a", ru: "находиться в уставшем состоянии" },
        { es: "estar casado", ru: "быть женатым/замужем" },

        { es: "Quedarse", ru: "оставаться", tag: "v" },
        { es: "yo me quedo", ru: "я остаюсь" },
        { es: "tú te quedas", ru: "ты остаешься" },
        { es: "él se queda", ru: "он остается" },
        { es: "nosotros nos quedamos", ru: "мы остаемся" },
        { es: "vosotros os quedais", ru: "вы остаетесь" },
        { es: "ellos se quedan", ru: "они остаются" },

        { es: "cuando", ru: "когда" },
        { es: "carta", ru: "письмо" },

        { es: "Escribir", ru: "писать", tag: "v" },
        { es: "yo escribo", ru: "я пишу" },
        { es: "tú escribes", ru: "ты пишешь" },
        { es: "él escribe", ru: "он пишет" },
        { es: "nosotros escribimos", ru: "мы пишем" },
        { es: "vosotros escribís", ru: "вы пишете" },
        { es: "ellos escriben", ru: "они пишут" },
    ],
    "Lección 6": [
        { es: "normalmente", ru: "обычно" },
        { es: "un colegio", ru: "школа", tag: "n" },
        { es: "una escuela", ru: "школа чего-то", tag: "n" },
        { es: "... en punto", ru: "... ровно (о времени)" },
        { es: "... y media", ru: "... с половиной" },
        { es: "... y cuarto", ru: "... с четвертью" },
        { es: "veinte", ru: "двадцать" },
        { es: "veinticinco", ru: "двадцатьпять" },
        { es: "¿Qué hora es/tienes?", ru: "Cколько времени?" },
        { es: "¿A qué hora?", ru: "когда/во сколько?" },
        { es: "perdone/disculpe", ru: "прощу прощения" },
        { es: "de la mañana", ru: "утром" },
        { es: "de la tarde", ru: "днем" },
        { es: "de la noche", ru: "вечером" },
        { es: "de la madrugada", ru: "ночью" },
    ],
    "Lección 7": [
        { es: "Trabajar", ru: "работать", tag: "v" },
        { es: "ir+a+infinitivo", ru: "собираюсь+что-то+делать" },
        { es: "un paseo", ru: "прогулка", tag: "n"  },
        { es: "la hora de la comida", ru: "обеденное время" },

        { es: "Volver", ru: "возвращаться", tag: "v" },
        { es: "yo vuelvo", ru: "я возвращаюсь" },
        { es: "tú vuelves", ru: "ты возвращаешься" },
        { es: "él vuelve", ru: "он возвращается" },
        { es: "nosotros volvemos", ru: "мы возвращаемся" },
        { es: "vosotros volveis", ru: "вы возвращаетесь" },
        { es: "ellos vuelven", ru: "они возвращаются" },

        { es: "cada", ru: "каждый" },
        { es: "", ru: "" },

        { es: "Jugar", ru: "играть", tag: "v" },

        { es: "Gustarse", ru: "нравиться", tag: "v" },
        { es: "A mi me gusta+infinitivo", ru: "мне нравиться ..." },
        { es: "A tí te gusta+infinitivo", ru: "тебе нравиться ..." },
        { es: "A él le gusta+infinitivo", ru: "ему нравиться ..." },
        { es: "A nosotros nos gusta+infinitivo", ru: "нам нравиться ..." },
        { es: "A vosotros os gusta+infinitivo", ru: "вам нравиться ..." },
        { es: "A ellos les gusta+infinitivo", ru: "им нравиться ..." },

        { es: "Ver", ru: "смотреть", tag: "v" },
        { es: "yo veo", ru: "я смотрю" },
        { es: "tú ves", ru: "ты смотришь" },
        { es: "él ve", ru: "он смотрит" },
        { es: "nosotros vemos", ru: "мы смотрим" },
        { es: "vosotros veis", ru: "вы смотрите" },
        { es: "ellos ven", ru: "они смотрят" },

        { es: "el televisor", ru: "телевизор", tag: "n" },
        { es: "la televisión", ru: "телевидение", tag: "n" },
        { es: "unos vaqueros", ru: "джинсы", tag: "n" },
    ],
    "Lección 8": [
        { es: "desfile", ru: "парад", tag: "n" },
        { es: "fuegos artificiales", ru: "салют" },
        { es: "un petardo", ru: "петарда", tag: "n" },
        { es: "una tostada", ru: "тост", tag: "n" },
        { es: "con", ru: "с (предлог)" },
        { es: "la ropa", ru: "одежда" },
        { es: "tarde", ru: "позже" },
        { es: "una clase", ru: "класс" },
        { es: "adjectivo", ru: "прилагательное", tag: "n" },
        { es: "un hombre", ru: "мужчина", tag: "n" },
        { es: "un chico", ru: "мальчик", tag: "n" },
        { es: "una chica", ru: "девочка", tag: "n" },
        { es: "sincero", ru: "искренний", tag: "a" },
        { es: "alegre", ru: "веселый", tag: "a" },
        { es: "inteligente", ru: "умный", tag: "a" },
        { es: "educado", ru: "воспитанный", tag: "a" },
        { es: "gente", ru: "люди", tag: "n" },
        { es: "la educación", ru: "образование", tag: "a" },
        { es: "feliz", ru: "счастливый", tag: "a" },
        { es: "difícil", ru: "сложный", tag: "a" },
        { es: "fácil", ru: "легкий", tag: "a" },
        { es: "familiar", ru: "семейный", tag: "a" },
        { es: "pareja", ru: "пара", tag: "n" },
        { es: "alto", ru: "высокий", tag: "a" },
        { es: "bajo", ru: "низкий", tag: "a" },
        { es: "largo", ru: "длинный", tag: "a" },
        { es: "corto", ru: "коротнкий", tag: "a" },
        { es: "gordo", ru: "толстый", tag: "a" },
        { es: "delgado", ru: "худой", tag: "a" },
        { es: "azul", ru: "синий", tag: "a" },
        { es: "amarillo", ru: "желтый", tag: "a" },
        { es: "una pelicula", ru: "фильм", tag: "n" },
        { es: "aburrida", ru: "скучный", tag: "a" },
        { es: "Aburrirse", ru: "заскучать", tag: "v" },
        { es: "un traje", ru: "костюм", tag: "n" },
        { es: "estar constipado", ru: "схватить насморк" },
        { es: "estar resfriado", ru: "простудиться" },
        { es: "estar enfermo", ru: "заболеть" },
        { es: "una mesa", ru: "стол", tag: "n" },
        { es: "cama", ru: "кровать", tag: "n" },
        { es: "un traje", ru: "костюм", tag: "n" },
        { es: "un plato", ru: "тарелка", tag: "n" },
        { es: "una plata", ru: "серебро", tag: "n" },
        { es: "un cuchillo", ru: "нож", tag: "n" },
        { es: "una cuchara", ru: "ложка", tag: "n" },
        { es: "un tenedor", ru: "вилка", tag: "n" },
    ],
    "Lección 9": [
        { es: "Empezar", ru: "начинать", tag: "v" },
        { es: "yo empiezo", ru: "я начинаю" },
        { es: "tú empiezas", ru: "ты начинаешь" },
        { es: "él empieza", ru: "он начинает" },
        { es: "nosotros empezamos", ru: "мы начинаем" },
        { es: "vosotros empezais", ru: "вы начинаете" },
        { es: "ellos empiezan", ru: "они начинают" },
        { es: "un vaso", ru: "стакан", tag: "n" },
        { es: "sacar/pasar un examen", ru: "сдать экзамен" },
        { es: "muy", ru: "очень" },
        { es: "guapa", ru: "симпатичный" },
        { es: "fuerte", ru: "сильный", tag: "a" },
        { es: "caro", ru: "дорогой", tag: "a" },
        { es: "calle", ru: "улица", tag: "n" },
        { es: "un frigorífico", ru: "холодильник", tag: "n" },
        { es: "un congelador", ru: "морозильник", tag: "n" },
        { es: "Haber", ru: "There is", tag: "v" },
        { es: "mucho", ru: "много" },
        { es: "gente", ru: "люди" },
        { es: "hoy", ru: "сегодня" },
        { es: "por la tarde", ru: "днем" },
        { es: "cine", ru: "кинотеатр" },
        { es: "Comprar", ru: "покупать", tag: "v" },
    ],
    "Lección 10": [
        { es: "¿Quien?", ru: "Кто?" },
        { es: "¿Cómo?", ru: "Как?" },
        { es: "¿Cuando?", ru: "Когда?" },
        { es: "¿Cuantos?", ru: "Сколько?" },
        { es: "una tienda", ru: " магазин", tag: "n" },
        { es: "verano", ru: "лето", tag: "n" },
        { es: "invierno", ru: "зима", tag: "n" },
        { es: "todo", ru: "всё" },
        { es: "también", ru: "также" },

        { es: "Poder", ru: "мочь", tag: "v" },
        { es: "yo puedo", ru: "я могу" },
        { es: "tú puedes", ru: "ты можешь" },
        { es: "él puede", ru: "он может" },
        { es: "nosotros podemos", ru: "мы можем" },
        { es: "vosotros podeis", ru: "вы можете" },
        { es: "ellos pueden", ru: "они могут" },

        { es: "Leer", ru: "читать", tag: "v" },
        { es: "yo leo", ru: "я читаю" },
        { es: "tú lees", ru: "ты читаешь" },
        { es: "él lee", ru: "он читает" },
        { es: "nosotros leemos", ru: "мы читаем" },
        { es: "vosotros leéis", ru: "вы читаете" },
        { es: "ellos leen", ru: "они читают" },

        { es: "Ayudar", ru: "помогать", tag: "v" },

        { es: "una vaca", ru: "корова", tag: "n" },
        { es: "una carne", ru: "мясо", tag: "n" },
        { es: "una carne picada", ru: "фарш", tag: "n" },
        { es: "ternera", ru: "телятина", tag: "n" },
        { es: "cerdo", ru: "свинина", tag: "n" },
        { es: "pollo", ru: "курица", tag: "n" },
        { es: "mixta", ru: "смесь", tag: "n" },
        { es: "un pan", ru: "хлеб", tag: "n" },
        { es: "una mantequilla", ru: "масло", tag: "n" },

        // TODO: Comidas y bebidas
        /*
        agua
        huevos яйца
        leche молоко
        sopa суп
        verdura зелень овощи
        */
    ],
    "Lección 11": [
        { es: "Seguir", ru: "продолжать", tag: "v" },
        { es: "yo sigo", ru: "я продолжаю" },
        { es: "tú sigues", ru: "ты продолжаешь" },
        { es: "él sigue", ru: "он продолжает" },
        { es: "nosotros seguimos", ru: "мы продолжаем" },
        { es: "vosotros seguís", ru: "вы продолжаете" },
        { es: "ellos siguen", ru: "они продолжают" },

        { es: "Estudiar", ru: "учить", tag: "v" },
        { es: "Decir", ru: "сказать", tag: "v" },
        { es: "Pedir", ru: "просить", tag: "v" },
        { es: "Oír", ru: "слышать", tag: "v" },

        { es: "Traer", ru: "приносить", tag: "v" },
        { es: "yo traigo", ru: "я приносим" },
        { es: "tú traes", ru: "ты приносишь" },
        { es: "él trae", ru: "он приносит" },
        { es: "nosotros traemos", ru: "мы приносим" },
        { es: "vosotros traéis", ru: "вы приносите" },
        { es: "ellos traen", ru: "они приносят" },

        { es: "todavía", ru: "ещё" },
        { es: "siempre", ru: "всегда" },
    ],
    "Lección 12": [
        { es: "un libro", ru: "книга", tag: "n" },
        { es: "Tocar", ru: "играть на инструменте", tag: "v" },
        { es: "por teléfono", ru: "по телефону" },
        { es: "temprano", ru: "рано" },
        { es: "el fútbol", ru: "футбол", tag: "n" },

        { es: "tener que", ru: "долженствовать" },

        { es: "Acabarse", ru: "закончиться", tag: "v" },
        { es: "se acaba el partido", ru: "игра окончена" },

        { es: "Olvidar", ru: "забывать", tag: "v" },
        { es: "yo olvido", ru: "я забываю" },
        { es: "tú olvidas", ru: "ты забываешь" },
        { es: "él olvida", ru: "он забывает" },
        { es: "nosotros olvidamos", ru: "мы забываем" },
        { es: "vosotros olvidais", ru: "вы забываете" },
        { es: "ellos olvidan", ru: "они забывают" },

        { es: "Olvidarse", ru: "забываться", tag: "v" },
        { es: "a mi se me olvida...", ru: "мне забывается..." },
        { es: "a ti se te olvida...", ru: "тебе забывается..." },
        { es: "a él se le olvida...", ru: "ему забывается..." },
        { es: "a nosotros se nos olvida...", ru: "нам забывается..." },
        { es: "a vosotros se os olvida...", ru: "вам забывается..." },
        { es: "a ellos se les olvida...", ru: "им забывается..." },
    ],
    "Lección 13": [
        { es: "Abrir", ru: "открывать", tag: "v" },
        { es: "Apagar", ru: "выключать", tag: "v" },
        { es: "una ventana", ru: "окно", tag: "n" },
        { es: "la luz", ru: "свет", tag: "n" },
        { es: "una oficina", ru: "офис", tag: "n" },
        { es: "una helado", ru: "мороженное", tag: "n" },
        { es: "un pimiento", ru: "перец", tag: "n" },
        { es: "un pepino", ru: "огурец", tag: "n" },
        { es: "un tomate", ru: "помидор", tag: "n" },
        { es: "verde", ru: "зеленый", tag: "a" },
        { es: "relleno", ru: "начиненный", tag: "a" },
        { es: "vez", ru: "раз" },
        { es: "dos veces", ru: "два раза" },
        { es: "una pechuga", ru: "грудка" },
        { es: "a la plancha", ru: "на гриле" },
        { es: "patatas fritas", ru: "картошка фри" },
        { es: "una ensalada rusa", ru: "салат Оливье" },
        { es: "un filete ruso", ru: "котлета" },

        { es: "Querer", ru: "хотеть", tag: "v" },
        { es: "yo quiero", ru: "я хочу" },
        { es: "tú quieres", ru: "ты хочешь" },
        { es: "él quiere", ru: "он хочет" },
        { es: "nosotros queremos", ru: "мы хотим" },
        { es: "vosotros quereis", ru: "вы хотите" },
        { es: "ellos quieren", ru: "они хотят" },
    ],
    "Lección 14": [
        { es: "una ciudad", ru: "город", tag: "n" },
        { es: "ahí", ru: "там" },
        { es: "aquí", ru: "здесь" },
        { es: "luego", ru: "затем" },
        { es: "bien", ru: "хорошо" },
        { es: "mal", ru: "плохо" },
        { es: "alguien", ru: "кто-то" },
        { es: "cafetería", ru: "кофейня", tag: "n" },
        { es: "jefe", ru: "босс", tag: "n" },
        { es: "un trozo", ru: "кусок", tag: "n" },
        { es: "tarta", ru: "торт", tag: "n" },
        { es: "una frambuesa", ru: "малина", tag: "n" },
        { es: "por eso", ru: "поэтому" },

        { es: "Quedar", ru: "встречаться", tag: "v" },
        { es: "Viajar", ru: "путешествовать", tag: "v" },

        { es: "Quedarse bien con alguien", ru: "оставаться в хороших отношиениях с кем-то" },
        { es: "Quedarse mal con alguien", ru: "терять лицо перед кем-то" },

        { es: "Llevarse bien con alguien", ru: "ладить с кем-то" },

        { es: "Tener ganas", ru: "иметь охоту, желание" },

        { es: "Apetecerse", ru: "иметь желание (про еду)" },
        { es: "Me apetecen los helados", ru: "Мне нравятся мороженные" },

    ],
};

/*
        { es: "", ru: "" },
        { es: "", ru: "", tag: "n" },
        { es: "", ru: "", tag: "a" },

        { es: "", ru: "", tag: "v" },
        { es: "yo ", ru: "я " },
        { es: "tú ", ru: "ты " },
        { es: "él ", ru: "он " },
        { es: "nosotros ", ru: "мы " },
        { es: "vosotros ", ru: "вы " },
        { es: "ellos ", ru: "они " },

        { es: "yo me ", ru: "я " },
        { es: "tú te ", ru: "ты " },
        { es: "él se ", ru: "он " },
        { es: "nosotros nos ", ru: "мы " },
        { es: "vosotros os ", ru: "вы " },
        { es: "ellos se ", ru: "они " },
*/